### ISSUE TITLE
ndarray version of FAOSTAT Food Balance Sheets 

### ISSUE THREAD

**Issue by jucordero** [FixOurFood/AgriFoodPy#12]
Current output of the FAO data reading notebook is a CSV file, which doesn't address the issue of complex navigation as a function of the different slices through the data: year, food item, element, region.

Options exist to add multidimensionality to the arrays: python ndarray is the simplest one, but alternatives include the use of labels for human readable indexing, like Xarray and Pandas MultiIndex.

- [x] Duplicate the Reading_FAOSTAT_data notebook and implement a multidimensional, label based indexing 
- [x] Output an array that can be read in the same format by the package
- [ ] Store values in different units. Does it make sense to store all unts? ({g, kcal, gprot, gfat} / capita / day ) or should those be computed by the user?

**Comment by jucordero** [comment]
In my opinion, additional units should be

**Comment by kaedonkers** [comment]
NetCDF might be an option for storing these ndarrays. Arbitrary attributes can be added to the arrays stored in the NetCDF file, of which the `units` attributes is universally recognised in tools which load NetCDF (such as Xarray).

**Comment by jucordero** [comment]
Already generated a NetCDF file for FAOSTAT and other datasets in the package.
Will move some of the issues related to data format to the afp-data repo. and closed this as completed for now
