### ISSUE TITLE
Documentation for Installation and contribution

### ISSUE THREAD

**Issue by jucordero** [FixOurFood/AgriFoodPy#15]
Readthedocs for:
- [ ] Installation instructions
- [ ] Contribution guidelines

Is it worth adding a wiki too?

**Comment by kaedonkers** [comment]
Readthedocs is certainly a good standard tool for documentation, but perhaps we can add these sections to the main README first? Means we make the content available with minimal effort, and move the information to a seperate readthedocs website when we have resource/require more comprehensive docs

**Comment by kaedonkers** [comment]
Autogenerate documentation tools might be useful here:
e.g. https://medium.com/blueriders/python-autogenerated-documentation-3-tools-that-will-help-document-your-project-c6d7623814ef
