### ISSUE TITLE
Feature: Host notebook examples on Binder

### ISSUE THREAD

**Issue by kaedonkers** [FixOurFood/AgriFoodPy#19]
Binder could provide an easy interface for users to access AgriFoodPy examples without having to download any data.

A quick example is here at this URL (will take a wee while to spin up):
https://mybinder.org/v2/gh/FixOurFood/AgriFoodPy/HEAD

TODOs to make this a working solution:
- [ ] Ensure that notebooks install all packages from current directory structure
- [ ] Make `agrifoodpy` an installable package and install it in the Binder environment
- [ ] Add Binder badges to the repo README
- [ ] Configure the Binder with the additional features we want e.g. Voila support
- [ ] Assess whether the free infrastructure meets our user interface demands

**Comment by jucordero** [comment]
We talked about this in a meeting, but it is probably best to keep the examples in a separate repository?
In the meantime, I've created https://github.com/FixOurFood/agrifoodpy-examples inside the FixOurFood github organisation.

I'll be copying the notebooks to that repository to make them easier to navigate.

**Comment by kaedonkers** [comment]
A separate examples repository is certainly one sensible way to organise this, particularly if you wish to make this an installable Python package. If you use Binder to render the notebooks, this makes even more sense as there are `.binder` config files which can live outside the `agrifoodpy` package repo

**Comment by jucordero** [comment]
We discussed this in person this week:

You can pip install a development version of package directly from GitHub
See: https://stackoverflow.com/a/50141879/9058478
Add the following to the development environment.yml:
```
dependencies:
  - pip
  - pip:
    - git+git://github.com/FixOurFood/AgriFoodPy@main

```

**Comment by jucordero** [comment]
Just pushed the first example and tested the binder deployment of agrifoodpy-examples.
The binder can be found here:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/FixOurFood/agrifoodpy-examples/main)
