### ISSUE TITLE
Prepare setup.py, pyproject.toml, setup.cfg for version 0.1 distribution

### ISSUE THREAD

**Issue by jucordero** [FixOurFood/AgriFoodPy#24]
In order to package AgriFoodPy for publication in PyPI we must decide on the backend to build the package and create/modify the configuration files accordingly.

- [x] Define the backend
- [x] Create setup.cfg if necessary
- [x] Create pyproject.toml if necessary
- [x] Modify setup.py to reflect version number and correct metadata

**Comment by kaedonkers** [comment]
Not sure if I shared this before, but I think this webbook is now the canonical source of Python packaging knowledge:
https://py-pkgs.org/

**Comment by jucordero** [comment]
I actually own a physical copy! Been looking at it frequently.

**Comment by jucordero** [comment]
Addressed in #55
