### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by jucordero** [FixOurFood/AgriFoodPy#25]
Setup CI on the repository. This includes automatic tests, style and possibly other checks

Will update this issues with a list of tasks once I dig deeper into this

**Comment by itrharrison** [comment]
Hi @jucordero I think I mentioned a while ago I would be happy to do this. I have enough practice now I think I could set it up fairly quickly, so let me know if it would still be useful 👍.

**Comment by jucordero** [comment]
Hi Ian! thanks for the reminder! I vividly remember I said it would take me a couple of weeks to give it a try and three months have passed :disappointed: . My bad

I thought I had created a draft PR with my experiments before.
Just submitted a draft PR with a simple implementation of github actions + tox + pytest.

**Comment by jucordero** [comment]
#45 added the minimal code to do automatic testing and documentation building. Will close this for now
