### ISSUE TITLE
Unable to import FoodBalanceSheet

### ISSUE THREAD

**Issue by jsun** [FixOurFood/AgriFoodPy#62]
I'm trying AgriFoodPy following the Usage written in README, but I get the following import error. Is there anything I can do to address this error on my end?

```
(agrifoodpy) LC:~/Desktop/agrifoodpy$ python
Python 3.11.4 (main, Jul  7 2023, 12:16:42) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from agrifoodpy.food import FoodBalanceSheet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'FoodBalanceSheet' from 'agrifoodpy.food' (/Users/xxx/.pyenv/versions/agrifoodpy/lib/python3.11/site-packages/agrifoodpy/food/__init__.py)
>>> from agrifoodpy_data.food import FAOSTAT
```

**Comment by jucordero** [comment]
Hi @jsun and thanks for reporting this.
The issue is in the code snippet in the README.

The import statement should be
```python
...
from agrifoodpy.food.food import FoodBalanceSheet
...
```
note the extra `.food`
I've pushed changes to the README and made sure the examples run in a fresh environment

**Comment by jsun** [comment]
thx to update the README and I could import `FoodBalanceSheet` now.
